import Taro from "@tarojs/taro";
//缓存常量
export const TOKEN = "TOKEN";
export const USER = "USER";
export const LOCALE = "LOCALE";
export const LOCALEID = "LOCALEID";
export const CURRENCY = "CURRENCY";
//store常量
export const REQUEST_PRODUCT_CATEGORY = "REQUEST_PRODUCT_CATEGORY";
export const CHANGE_PRODUCT_CATEGORY = "CHANGE_PRODUCT_CATEGORY";
export const CHANGE_PRODUCT_CATEGORY_LOADING =
  "CHANGE_PRODUCT_CATEGORY_LOADING";
export const CHANGE_PRODUCT_LIST = "CHANGE_PRODUCT_LIST";
export const CHANGE_PRODUCT_DETAIL = "CHANGE_PRODUCT_DETAIL";
export const CHANGE_PRODUCT_LOADING = "CHANGE_PRODUCT_LOADING";
export const CHANGE_CART_LOADING = "CHANGE_CART_LOADING";
export const CHANGE_CART_LIST = "CHANGE_CART_LIST";
export const CHANGE_CART_ = "CHANGE_CART_SELECTED";
export const CHANGE_ORDER_ADDRESS = "CHANGE_ORDER_ADDRESS";
export const CHANGE_ORDER_PAYMENT = "CHANGE_ORDER_PAYMENT";
export const CHANGE_ORDER_DELIVERY = "CHANGE_ORDER_DELIVERY";
export const CHANGE_ORDER_SELECTED_ADDRESS = "CHANGE_ORDER_SELECTED_ADDRESS";
export const CHANGE_ORDER_CART_INFO = "CHANGE_ORDER_CART_INFO";

export const CHANGE_COUPONS_LIST_LOADING = "CHANGE_COUPONS_LIST_LOADING";
export const CHANGE_COUPONS_LIST = "CHANGE_COUPONS_LIST";

export const CHANGE_FROUM_CATEGORY = "CHANGE_FROUM_CATEGORY";
export const CHANGE_FROUM_CATEGORY_LOADING = "CHANGE_FROUM_CATEGORY_LOADING";

export const CHANGE_FROUM_POST = "CHANGE_FROUM_POST";
export const CHANGE_FROUM_POST_LOADING = "CHANGE_FROUM_POST_LOADING";

export const CHANGE_POST_DETAIL = "CHANGE_POST_DETAIL";
export const CHANGE_POST_DETAIL_LOADING = "CHANGE_POST_DETAIL_LOADING";

export const REQUEST_HOMEPRODUCT = "REQUEST_HOMEPRODUCT";
export const CHANGE_HOMEPRODUCT = "CHANGE_HOMEPRODUCT";
export const CHANGE_HOMEPRODUCT_LOADING = "CHANGE_HOMEPRODUCT_LOADING";

export const REQUEST_SEARCHPRODUCT = "REQUEST_SEARCHPRODUCT";
export const CHANGE_SEARCHPRODUCT = "CHANGE_SEARCHPRODUCT";
export const CHANGE_SEARCHPRODUCT_LOADING = "CHANGE_SEARCHPRODUCT_LOADING";

//设备信息
export const SCREEN_HEIGHT = Taro.getSystemInfoSync().screenHeight;
export const SCREEN_WIDTH = Taro.getSystemInfoSync().screenWidth;
export const WINDOW_WIDTH = Taro.getSystemInfoSync().windowWidth; //可用宽度
export const WINDOW_HEIGHT = Taro.getSystemInfoSync().windowHeight; //可用高度

export const CHANGE_WISH_LIST = "CHANGE_WISH_LIST";
export const CHANGE_WISH_LIST_LOADING = "CHANGE_WISH_LIST_LOADING";

export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
export const CHANGE_CURRENCY_LOADING = "CHANGE_CURRENCY_LOADING";

export const CHANGE_BALANCE = "CHANGE_BALANCE";
export const CHANGE_BALANCE_LOADING = "CHANGE_BALANCE_LOADING";

export const REQUEST_SYSTEM_NOTIFICATION = "REQUEST_SYSTEM_NOTIFICATION";
export const CHANGE_SYSTEM_NOTIFICATION = "CHANGE_SYSTEM_NOTIFICATION";
export const CHANGE_SYSTEM_NOTIFICATION_LOADING =
  "CHANGE_SYSTEM_NOTIFICATION_LOADING";
export const REQUEST_SYSTEM_UNREAD_NOTIFICATION =
  "REQUEST_SYSTEM_UNREAD_NOTIFICATION";
export const CHANGE_SYSTEM_UNREAD_NOTIFICATION =
  "CHANGE_SYSTEM_UNREAD_NOTIFICATION";
export const CHANGE_SYSTEM_UNREAD_NOTIFICATION_LOADING =
  "CHANGE_SYSTEM_UNREAD_NOTIFICATION_LOADING";
export const REQUEST_MY_NOTIFICATION = "REQUEST_MY_NOTIFICATION";
export const CHANGE_MY_NOTIFICATION = "CHANGE_MY_NOTIFICATION";
export const CHANGE_MY_NOTIFICATION_LOADING = "CHANGE_MY_NOTIFICATION_LOADING";
export const REQUEST_MY_UNREAD_NOTIFICATION = "REQUEST_MY_UNREAD_NOTIFICATION";
export const CHANGE_MY_UNREAD_NOTIFICATION = "CHANGE_MY_UNREAD_NOTIFICATION";
export const CHANGE_MY_UNREAD_NOTIFICATION_LOADING =
  "CHANGE_MY_UNREAD_NOTIFICATION_LOADING";

export const CHANGE_BANNER = "CHANGE_BANNER";
export const CHANGE_BANNER_LOADING = "CHANGE_BANNER_LOADING";
