export default defineAppConfig({
  pages: [
    "pages/index/index",
    "pages/index/find/find",
    "pages/index/messages/messages",
    "pages/index/cart/cart",
    "pages/index/user/user",
    "pages/index/active-router/active-router",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "WeChat",
    navigationBarTextStyle: "black",
    navigationStyle: "custom",
  },
  tabBar: {
    color: "#666",
    selectedColor: "#D62C75",
    backgroundColor: "#fafafa",
    borderStyle: "black",
    list: [
      {
        pagePath: "pages/index/index",
        iconPath: "./assets/tab-bar/home.png",
        selectedIconPath: "./assets/tab-bar/home-active.png",
        text: "Home",
      },
      {
        pagePath: "pages/index/find/find",
        iconPath: "./assets/tab-bar/find.png",
        selectedIconPath: "./assets/tab-bar/find-active.png",
        text: "Social",
      },
      {
        pagePath: "pages/index/messages/messages",
        iconPath: "./assets/tab-bar/messages.png",
        selectedIconPath: "./assets/tab-bar/messages-active.png",
        text: "Message",
      },
      {
        pagePath: "pages/index/cart/cart",
        iconPath: "./assets/tab-bar/cart.png",
        selectedIconPath: "./assets/tab-bar/cart-active.png",
        text: "Cart",
      },
      {
        pagePath: "pages/index/user/user",
        iconPath: "./assets/tab-bar/me.png",
        selectedIconPath: "./assets/tab-bar/me-active.png",
        text: "My",
      },
    ],
  },
  subPackages: [
    {
      root: "pages/about-order/",
      pages: [
        "confirm-order/confirm-order",
        "orders/orders",
        "order-detail/order-detail",
        "coupons/coupons",
        "bulk-list/index",
        "bulk-detail/bulk-detail",
        "bulk-order/bulk-order",
        "bargain-list/bargain-list",
        "bargain-detail/bargain-detail",
        "bargain-share-post/bargain-share-post",
        "bargain-order/bargain-order",
        "charge-balance/charge-balance",
      ],
    },
    {
      root: "pages/about-personal/",
      pages: [
        "user-login/user-login",
        "email-register/email-register",
        "phone-register/phone-register",
        "forget-password/forget-password",
        "settings/index",
        "settings/about-us/about-us",
        "settings/change-email/change-email",
        "settings/change-password/change-password",
        "settings/change-phone/change-phone",
        "settings/clear-cache/clear-cache",
        "settings/feedback/feedback",
        "settings/swith-language/swith-language",
        "settings/user-info/user-info",
        "address/address-list/address-list",
        "address/add-address/add-address",
        "address/update-address/update-address",
        "help/help",
        "contact-us/contact-us",
        "rewardpoints/rewardpoints",
        "balances/balances",
        "chat/chat",
      ],
    },
    {
      root: "pages/about-product/",
      pages: [
        "product-detail/product-detail",
        "product-list/product-list",
        "search-product/search-product",
        "wish-list/wish-list",
        "history-list/history-list",
      ],
    },
    {
      root: "pages/about-find/",
      pages: [
        "find-detail/find-detail",
        "my-post/my-post",
        "publish-post/publish-post",
        "my-reply/my-reply",
        "my-liked/my-liked",
        "my-favorited/my-favorited",
        "be-liked/be-liked",
        "be-favorited/be-favorited",
        "my-following/my-following",
        "my-fans/my-fans",
        "customer-space/customer-space",
      ],
    },
  ],
});
